name: API Crawling Details Project Carz Schedule
on:
  schedule:
    - cron: 0 0 * * 6 # Runs at 12 AM (midnight) every Saturday
    # - cron: '* * * * *' # Runs every minute

  workflow_dispatch:
    inputs:
      reason:
        description: "Fill reason here!!!!!!"
        required: false
permissions:
  contents: write
  actions: write
jobs:
  pre-deployment:
    name: Pre Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Notification to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "🚀 - Start crawling data by API..."
  crawler:
    needs: [pre-deployment]
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        os:
          [
            { name: ubuntu-latest, chunk: 0 },
            { name: ubuntu-latest, chunk: 1 },
            { name: ubuntu-latest, chunk: 2 },
            { name: ubuntu-latest, chunk: 3 },
            { name: ubuntu-latest, chunk: 4 },
            { name: ubuntu-latest, chunk: 5 },
            { name: ubuntu-latest, chunk: 6 },
            { name: ubuntu-latest, chunk: 7 },
            { name: ubuntu-latest, chunk: 8 },
            { name: ubuntu-latest, chunk: 9 },
            { name: ubuntu-latest, chunk: 10 },
            { name: ubuntu-latest, chunk: 11 },
            { name: ubuntu-latest, chunk: 12 },
            { name: ubuntu-latest, chunk: 13 },
            { name: ubuntu-latest, chunk: 14 },
            { name: ubuntu-latest, chunk: 15 },
            { name: ubuntu-latest, chunk: 16 },
            { name: ubuntu-latest, chunk: 17 },
            { name: ubuntu-latest, chunk: 18 },
            { name: ubuntu-latest, chunk: 19 },
            { name: ubuntu-latest, chunk: 20 },
          ]
    runs-on: ${{ matrix.os.name }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: "LibertyCarz/nestjs-carz-crawler"
          token: ${{ secrets.GH_TOKEN }}
          ref: "main"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0

      # - name: Install dependencies
      #   run: npm install --force

      - name: Start NestJS application
        run: |
          node -v
          echo "const {crawlData} = require('./crawls/crawl-by-api'); crawlData(${{ matrix.os.chunk }});" > main.js
          node main.js

      - name: Switch git user to github action.
        working-directory: nestjs-carz-crawler-action
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Switch to new Branch.
        working-directory: nestjs-carz-crawler-action
        run: |
          git push origin --delete chunk/data-crawler-${{ matrix.machine.chunk }} || echo "Error"
          git checkout --orphan chunk/data-crawler-${{ matrix.machine.chunk }}
          git reset

      - name: Copy file
        run: |
          if [ -e "nestjs-carz-crawler/${{ matrix.machine.chunk }}.cars-data-crawler.csv" ]; then
            cp nestjs-carz-crawler/${{ matrix.machine.chunk }}.cars-data-crawler.csv nestjs-carz-crawler-action/
          else
            touch nestjs-carz-crawler-action/${{ matrix.machine.chunk }}.cars-data-crawler.csv
          fi

      - name: Push to chunk/data-crawler-${{ matrix.machine.chunk }}.
        working-directory: nestjs-carz-crawler-action
        run: |
          git add ${{ matrix.machine.chunk }}.cars-data-crawler.csv
          git commit -m "✅ - Save crawler data."
          git push origin chunk/data-crawler-${{ matrix.machine.chunk }}

      - name: Failure notification
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "💣 - Failure crawling data by API(${{ matrix.os.chunk }})."

  finish:
    needs: [crawler]
    name: Send Notification Result
    runs-on: ubuntu-latest
    steps:
      after-crawler:
      needs: [pre-crawler, crawler]
      if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
      name: After Crawler
      runs-on: ubuntu-latest
      steps:
        - name: Clone nestjs-carz-crawler-action.
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.GH_TOKEN }}
            path: nestjs-carz-crawler-action
            ref: main
  
        - name: Cleaup.
          working-directory: nestjs-carz-crawler-action
          run: |
            rm -rf data
            mkdir data
  
        - name: Loop clone.
          run: |
            for i in {1..${{ needs.pre-crawler.outputs.number-machines }}}
            do
              git clone -b chunk/data-crawler-$i  https://LibertyCarz:${{ secrets.GH_TOKEN }}@github.com/LibertyCarz/nestjs-carz-crawler-action.git chunk-$i
              cp chunk-$i/$i.cars-data-crawler.csv nestjs-carz-crawler-action/data/
            done
  
        - name: Merge files
          working-directory: nestjs-carz-crawler-action/data
          run: |
            cat 1.cars-data-crawler.csv >>cars-data-crawler.csv
            for i in {2..${{needs.pre-crawler.outputs.number-machines}}};
            do
              tail -n +2 "$i.cars-data-crawler.csv" >>cars-data-crawler.csv
            done
  
        - name: Switch git user to github action.
          working-directory: nestjs-carz-crawler-action
          run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
  
        - name: Push
          working-directory: nestjs-carz-crawler-action
          run: |
            git add -A
            git commit -m "✅ - Save crawler data."
            git push origin main || echo "Error"
  
        - name: Remove Chunk branch
          working-directory: nestjs-carz-crawler-action
          run: |
            git fetch
            git branch -r | grep 'origin' | grep -v 'main$' | grep -v HEAD | cut -d/ -f2- | while read line; do git push origin :heads/$line; done;
  
        - name: Notification to telegram
          uses: PacificPromise/macos-telegram-action@main
          with:
            type: topic
            message: "✅ Success crawling data Khmer24: ${{ needs.pre-crawler.outputs.message }}"
