name: Project Carz Schedule Crawler data
on:
  schedule:
    - cron: 0 0 * * 1 # Runs at 12 AM (midnight) every Monday

  workflow_dispatch:
    inputs:
      number-machines:
        description: "Total number of machines"
        required: True
        default: "10"

  push:
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  pre-deployment:
    name: Pre Deployment
    runs-on: ubuntu-latest
    outputs:
      number-machines: ${{ steps.number-machines.outputs.value }}
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - name: Calculation inputs number machines.
        id: number-machines
        run: |
          NUMBER=10
          if [ "${{ github.event.inputs.number-machines }}" ]; then
            NUMBER=${{ github.event.inputs.number-machines }}
          fi
          echo "value=$NUMBER" >> $GITHUB_OUTPUT

      - name: Calculation machines.
        id: matrix
        run: |
          MATRIX="{\"name\":\"ubuntu-latest\",\"chunk\":1}"
          for i in {2..${{ steps.number-machines.outputs.value }}}
          do
            MATRIX="$MATRIX,{\"name\":\"ubuntu-latest\",\"chunk\":$i}"
          done
          echo "value=[ $MATRIX ]" >> $GITHUB_OUTPUT

      - name: Echo all value.
        run: |
          echo Number of machines: ${{ steps.number-machines.outputs.value }}
          echo Matrix: ${{ steps.matrix.outputs.value }}

      # - name: Notification to telegram
      #   uses: appleboy/telegram-action@master
      #   with:
      #     to: ${{ secrets.TELEGRAM_CHANNEL }}
      #     token: ${{ secrets.TELEGRAM_TOKEN }}
      #     message: "🚀 - Start crawling data Khmer24..."

  crawler:
    needs: [pre-deployment]
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        machine: ${{ fromJson(needs.pre-deployment.outputs.matrix) }}
    runs-on: ${{ matrix.machine.name }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: "LibertyCarz/nestjs-carz-crawler"
          token: ${{ secrets.GH_TOKEN }}
          ref: "main"
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18.12.0
  #     - name: Install dependencies
  #       run: npm install --force
  #     - name: Start NestJS application
  #       run: |
  #         node -v
  #         echo "const crawler = require('./crawl'); crawler.createData(${{ matrix.os.chunk }});" > crawler${{ matrix.os.chunk }}.js
  #         node crawler${{ matrix.os.chunk }}

  #     - name: Push changes
  #       run: |
  #         du -h ./${{ matrix.os.chunk }}.cars-data-crawler.csv
  #         git config --global user.email "github-actions[bot]@users.noreply.github.com"
  #         git config --global user.name "github-actions[bot]"
  #         git push origin --delete feat/data-crawler-${{ matrix.os.chunk }} || echo "Error"
  #         git branch -d feat/data-crawler-${{ matrix.os.chunk }} || echo "Error"
  #         git checkout -b feat/data-crawler-${{ matrix.os.chunk }}
  #         git add ./${{ matrix.os.chunk }}.cars-data-crawler.csv
  #         git commit -m "✅ - Save crawler data."
  #         git push --set-upstream origin feat/data-crawler-${{ matrix.os.chunk }} || echo "Error"
  #         cat ./${{ matrix.os.chunk }}.cars-data-crawler.csv

  #     - name: Failure notification
  #       if: ${{ failure() }}
  #       uses: appleboy/telegram-action@master
  #       with:
  #         to: ${{ secrets.TELEGRAM_CHANNEL }}
  #         token: ${{ secrets.TELEGRAM_TOKEN }}
  #         message: "💣 - Failure crawling data Khmer24(${{ matrix.os.chunk }})."
  # finish:
  #   needs: [crawler]
  #   name: Send Notification Result
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Succesfully notification
  #       uses: appleboy/telegram-action@master
  #       with:
  #         to: ${{ secrets.TELEGRAM_CHANNEL }}
  #         token: ${{ secrets.TELEGRAM_TOKEN }}
  #         message: "✅ - Success crawling data Khmer24."
